/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report database and queue health; sets `Cache-Control: no-store`.
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CheckOut
         * @description One named check in the `/health` response.
         */
        CheckOut: {
            /** Detail */
            detail: string | null;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "down";
        };
        /**
         * ChecksOut
         * @description Every check `/health` reports.
         */
        ChecksOut: {
            database: components["schemas"]["CheckOut"];
            queue: components["schemas"]["CheckOut"];
        };
        /**
         * HealthResponse
         * @description The `GET /health` response body: never exposes secrets or connection strings.
         */
        HealthResponse: {
            checks: components["schemas"]["ChecksOut"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
