"""Export the app's OpenAPI schema (Task 6).

    python -m autoapplier.api.export_openapi [--out PATH]   # stdout if --out is omitted

`FastAPI.openapi()` only inspects routes and Pydantic models: it never runs the lifespan,
so this needs no database or Valkey. `backend/openapi.json` is committed and generated by
`npm run gen:openapi`; `tests/unit/test_openapi_snapshot.py` fails if it drifts from the app.
"""

import argparse
import json
import sys
from pathlib import Path

from autoapplier.api.app import create_app
from autoapplier.config import Settings


def export_openapi() -> str:
    """Return the app's OpenAPI schema as pretty, key-sorted, newline-terminated JSON."""
    spec = create_app(Settings(_env_file=None)).openapi()
    return json.dumps(spec, indent=2, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Export the API's OpenAPI schema.")
    parser.add_argument("--out", type=Path, default=None, help="write here instead of stdout")
    args = parser.parse_args(argv)

    spec = export_openapi()
    if args.out is None:
        sys.stdout.write(spec)
    else:
        args.out.write_text(spec)


if __name__ == "__main__":
    main()
